const fs=require('fs');
const path=require('path');
const src=path.join(__dirname,'server.js');
const out=path.join(__dirname,'.runtime-files-server.js');
let code=fs.readFileSync(src,'utf8');
const helper=`app.use(express.json({ limit: '20mb' }));
const RECEIPTS_DIR=process.env.RECEIPTS_DIR||path.join(__dirname,'receipts');
function receiptExt(r){const n=String(r&&r.name||'').toLowerCase();if(n.endsWith('.pdf'))return 'pdf';if(r&&r.type==='image/png')return 'png';if(r&&r.type==='image/webp')return 'webp';return 'jpg'}
async function saveReceiptFile(r,id,tag){if(!r||r.url)return r;if(!r.data||!String(r.data).startsWith('data:'))return r;await fs.promises.mkdir(RECEIPTS_DIR,{recursive:true});const file=String(id).replace(/[^a-zA-Z0-9_-]/g,'')+'-'+tag+'-'+Date.now()+'-'+Math.random().toString(16).slice(2)+'.'+receiptExt(r);await fs.promises.writeFile(path.join(RECEIPTS_DIR,file),Buffer.from(String(r.data).split(',')[1]||'','base64'));return{name:r.name||file,type:r.type||'image/jpeg',storage:'file',filename:file,url:'/receipts/'+file}}
`;
if(!code.includes('saveReceiptFile'))code=code.replace("app.use(express.json({ limit: '20mb' }));",helper);
function swap(a,b,r){const s=code.indexOf(a),e=code.indexOf(b,s);if(s<0||e<0)throw Error('ruta no encontrada');code=code.slice(0,s)+r+code.slice(e)}
swap("app.post('/api/reservations/create'","\n\napp.post('/api/reservations/second-payment'",`app.post('/api/reservations/create',async(req,res)=>{try{const reservation=cleanReservation(req.body?.reservation||{});if(!reservation.numbers.length)return res.status(400).json({ok:false,error:'Selecciona números válidos.'});if(!['full','partial'].includes(reservation.paymentType))return res.status(400).json({ok:false,error:'Modalidad inválida.'});if(!reservation.name||!reservation.document||!reservation.phone||!reservation.paymentRef||!reservation.receipt)return res.status(400).json({ok:false,error:'Faltan datos o comprobante inválido.'});reservation.receipt=await saveReceiptFile(reservation.receipt,reservation.id,'inicial');const list=await readReservations();const busy=activeNumbers(list);const unavailable=reservation.numbers.filter(number=>busy.has(number));if(unavailable.length)return res.status(409).json({ok:false,error:'Números no disponibles: '+unavailable.join(', ')});list.unshift(reservation);await writeReservations(list);res.json({ok:true,reservation:publicReservation(reservation),reservations:list.map(publicReservation)})}catch(error){res.status(500).json({ok:false,error:error.message||'Error creando reserva.'})}});`);
swap("app.post('/api/reservations/second-payment'","\n\napp.post('/api/admin/action'",`app.post('/api/reservations/second-payment',async(req,res)=>{try{const{numbers,paymentRef,receipt}=req.body||{};const requested=Array.isArray(numbers)?numbers.map(n=>String(n).padStart(2,'0')).filter(n=>/^\\d{2}$/.test(n)):[];const baseReceipt=cleanReceipt(receipt);if(!requested.length||!baseReceipt)return res.status(400).json({ok:false,error:'Segundo pago inválido.'});const list=await readReservations();const updated=[];for(const number of requested){const idx=list.findIndex(r=>Array.isArray(r.numbers)&&r.numbers.includes(number)&&r.status==='partial');if(idx===-1)continue;const item=list[idx];const nums=Array.isArray(item.numbers)?item.numbers:[];const remaining=nums.filter(n=>n!==number);const id=String(Date.now())+Math.random().toString(16).slice(2);const rec={...item,id,status:'second_pending',numbers:[number],ticketTotal:20,amount:20,amountPaid:10,secondPaymentRef:cleanText(paymentRef,40),secondReceipt:await saveReceiptFile(baseReceipt,id,'segundo'),secondReportedAt:new Date().toISOString()};if(remaining.length){item.numbers=remaining;item.ticketTotal=remaining.length*20;item.amount=remaining.length*10;item.amountPaid=remaining.length*10;list.splice(idx,0,rec)}else list[idx]=rec;updated.push(number)}if(!updated.length)return res.status(404).json({ok:false,error:'No se encontraron números con pago parcial aprobado.'});await writeReservations(list);res.json({ok:true,updated,reservations:list.map(publicReservation)})}catch(error){res.status(500).json({ok:false,error:error.message||'Error reportando segundo pago.'})}});`);
fs.writeFileSync(out,code,'utf8');
require(out);
