const fs=require('fs');
const path=require('path');
let code=fs.readFileSync(path.join(__dirname,'server.js'),'utf8');
const runtime=path.join(__dirname,'.runtime-storage-server.js');
function cut(a,b,r){const s=code.indexOf(a),e=code.indexOf(b,s);if(s<0||e<0)throw new Error('No se localizo '+a);code=code.slice(0,s)+r+code.slice(e)}
const storage=`
const { S3Client, PutObjectCommand, GetObjectCommand, DeleteObjectCommand } = require('@aws-sdk/client-s3');
const STORAGE_BUCKET=process.env.STORAGE_BUCKET||process.env.S3_BUCKET||process.env.RAILWAY_OBJECT_STORAGE_BUCKET;
const STORAGE_ENDPOINT=process.env.STORAGE_ENDPOINT||process.env.S3_ENDPOINT||process.env.RAILWAY_OBJECT_STORAGE_ENDPOINT;
const STORAGE_REGION=process.env.STORAGE_REGION||process.env.S3_REGION||'auto';
const STORAGE_ACCESS_KEY_ID=process.env.STORAGE_ACCESS_KEY_ID||process.env.AWS_ACCESS_KEY_ID||process.env.S3_ACCESS_KEY_ID;
const STORAGE_SECRET_ACCESS_KEY=process.env.STORAGE_SECRET_ACCESS_KEY||process.env.AWS_SECRET_ACCESS_KEY||process.env.S3_SECRET_ACCESS_KEY;
const STORAGE_PUBLIC_BASE_URL=process.env.STORAGE_PUBLIC_BASE_URL||'';
const storageEnabled=!!(STORAGE_BUCKET&&STORAGE_ENDPOINT&&STORAGE_ACCESS_KEY_ID&&STORAGE_SECRET_ACCESS_KEY);
const s3=storageEnabled?new S3Client({region:STORAGE_REGION,endpoint:STORAGE_ENDPOINT,forcePathStyle:true,credentials:{accessKeyId:STORAGE_ACCESS_KEY_ID,secretAccessKey:STORAGE_SECRET_ACCESS_KEY}}):null;
function receiptExt(t){return t==='image/png'?'png':t==='image/webp'?'webp':t==='application/pdf'?'pdf':'jpg'}
function receiptBuffer(d){return Buffer.from(String(d||'').split(',')[1]||'','base64')}
async function storeReceiptFile(receipt,prefix){if(!receipt||!receipt.data||!storageEnabled)return receipt||null;const key='receipts/'+prefix+'-'+Date.now()+'-'+crypto.randomBytes(5).toString('hex')+'.'+receiptExt(receipt.type);await s3.send(new PutObjectCommand({Bucket:STORAGE_BUCKET,Key:key,Body:receiptBuffer(receipt.data),ContentType:receipt.type||'application/octet-stream'}));return {name:receipt.name,type:receipt.type,key,url:STORAGE_PUBLIC_BASE_URL?STORAGE_PUBLIC_BASE_URL.replace(/\\/$/,'')+'/'+key:'/api/admin/receipt-file?key='+encodeURIComponent(key)}}
async function deleteReceiptFile(receipt){if(!storageEnabled||!receipt||!receipt.key)return;try{await s3.send(new DeleteObjectCommand({Bucket:STORAGE_BUCKET,Key:receipt.key}))}catch(e){console.warn('delete receipt',e.message)}}
function hydrateReceiptUrl(receipt){if(!receipt)return receipt;if(receipt.key&&!receipt.url)return {...receipt,url:'/api/admin/receipt-file?key='+encodeURIComponent(receipt.key)};return receipt}
function hydrateAdminReceipts(list){return (list||[]).map(r=>({...r,receipt:hydrateReceiptUrl(r.receipt),secondReceipt:hydrateReceiptUrl(r.secondReceipt)}))}
app.get('/api/admin/receipt-file',requireAdmin,async(req,res)=>{try{if(!storageEnabled)return res.status(404).send('Storage no configurado');const key=String(req.query.key||'');const obj=await s3.send(new GetObjectCommand({Bucket:STORAGE_BUCKET,Key:key}));res.set('Content-Type',obj.ContentType||'application/octet-stream');res.set('Cache-Control','private, max-age=300');obj.Body.pipe(res)}catch(e){res.status(404).send('Comprobante no encontrado')}});
`;
code=code.replace("app.use(express.json({ limit: '20mb' }));","app.use(express.json({ limit: '20mb' }));\n"+storage);
cut("app.get('/api/admin/reservations'","\n\napp.post('/api/reservations/create'",`app.get('/api/admin/reservations', requireAdmin, async (_req, res) => {try{const reservations=await readReservations();res.set('Cache-Control','no-store');res.json({ok:true,reservations:hydrateAdminReceipts(reservations),storage:pool?'postgres':'file',objectStorage:storageEnabled})}catch(error){res.status(500).json({ok:false,error:error.message||'Error leyendo comprobantes.'})}});`);
cut("app.post('/api/reservations/create'","\n\napp.post('/api/reservations/second-payment'",`app.post('/api/reservations/create', async (req,res)=>{try{const reservation=cleanReservation(req.body?.reservation||{});if(!reservation.numbers.length)return res.status(400).json({ok:false,error:'Selecciona números válidos.'});if(!['full','partial'].includes(reservation.paymentType))return res.status(400).json({ok:false,error:'Modalidad inválida.'});if(!reservation.name||!reservation.document||!reservation.phone||!reservation.paymentRef||!reservation.receipt)return res.status(400).json({ok:false,error:'Faltan datos o comprobante inválido.'});reservation.receipt=await storeReceiptFile(reservation.receipt,reservation.id+'-inicial');const list=await readReservations();const busy=activeNumbers(list);const unavailable=reservation.numbers.filter(n=>busy.has(n));if(unavailable.length)return res.status(409).json({ok:false,error:'Números no disponibles: '+unavailable.join(', ')});list.unshift(reservation);await writeReservations(list);res.json({ok:true,reservation:publicReservation(reservation),reservations:list.map(publicReservation)})}catch(error){res.status(500).json({ok:false,error:error.message||'Error creando reserva.'})}});`);
cut("app.post('/api/reservations/second-payment'","\n\napp.post('/api/admin/action'",`app.post('/api/reservations/second-payment',async(req,res)=>{try{const{numbers,paymentRef,receipt}=req.body||{};const secondReceipt=cleanReceipt(receipt);const requested=Array.isArray(numbers)?numbers.map(n=>String(n).padStart(2,'0')).filter(n=>/^\\d{2}$/.test(n)):[];if(!requested.length||!secondReceipt)return res.status(400).json({ok:false,error:'Segundo pago inválido.'});const list=await readReservations();const updated=[];for(const number of requested){const idx=list.findIndex(r=>Array.isArray(r.numbers)&&r.numbers.includes(number)&&r.status==='partial');if(idx===-1)continue;const item=list[idx];const current=Array.isArray(item.numbers)?item.numbers:[];const selected=current.filter(n=>n===number);const remaining=current.filter(n=>n!==number);const stored=await storeReceiptFile(secondReceipt,item.id+'-'+number+'-segundo');const rec={...item,id:String(Date.now())+Math.random().toString(16).slice(2),status:'second_pending',numbers:selected,ticketTotal:selected.length*20,amount:selected.length*20,amountPaid:selected.length*10,secondPaymentRef:cleanText(paymentRef,40),secondReceipt:stored,secondReportedAt:new Date().toISOString()};if(remaining.length){item.numbers=remaining;item.ticketTotal=remaining.length*20;item.amount=remaining.length*10;item.amountPaid=remaining.length*10;list.splice(idx,0,rec)}else{list[idx]=rec}updated.push(number)}if(!updated.length)return res.status(404).json({ok:false,error:'No se encontraron números con pago parcial aprobado.'});await writeReservations(list);res.json({ok:true,updated,reservations:list.map(publicReservation)})}catch(error){res.status(500).json({ok:false,error:error.message||'Error reportando segundo pago.'})}});`);
const a=code.indexOf("app.post('/api/admin/action'");const b=code.indexOf("\n\napp.put('/api/reservations'",a);if(a>=0&&b>=0){let block=code.slice(a,b);block=block.replace("if (action === 'reset') {\n      await writeReservations([]);\n      return res.json({ ok: true, reservations: [] });\n    }","if (action === 'reset') {\n      for (const r of list) { await deleteReceiptFile(r.receipt); await deleteReceiptFile(r.secondReceipt); }\n      await writeReservations([]);\n      return res.json({ ok: true, reservations: [] });\n    }");block=block.replace("if (action === 'approve') {","if (action === 'delete') {\n      await deleteReceiptFile(item.receipt);\n      await deleteReceiptFile(item.secondReceipt);\n      list = list.filter(r => r.id !== id);\n    } else if (action === 'approve') {");code=code.slice(0,a)+block+code.slice(b)}
fs.writeFileSync(runtime,code,'utf8');
require(runtime);
